[package]
name = "roboarchive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
sane-scan = "0.1.1"
qoi = "0.4.1"
env_logger = "0.9.1"